updated conditional rendering
toletglobe/Tolet-Globe-Frontend pull request #21
Opened 2024-08-30 16:07 UTC by Pratishtha2616

2024-09-01 16:16 UTC, Pycreater requested changes
# Good Job just resolve the conflict's now.
## also remove the commented code to make it more clean and readable.

2024-09-01 19:06 UTC, shraddhaSarwade approved these changes

2024-09-05 05:36 UTC, Pycreater approved these changes

2024-09-05 10:59 UTC, shraddhaSarwade commented
Please raise PR in training branch

2024-09-05 10:59 UTC, closed without merging